FROM python:3.9.1-slim

RUN apt-get update -y && apt-get install wget build-essential git vim -y
#timezone
RUN cp /usr/share/zoneinfo/Asia/Seoul /etc/localtime && \
    echo "Asia/Seoul" > /etc/timezone
ENV PYTHONHASHSEED=random \
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PYTHONUNBUFFERED=1
RUN pip install --upgrade pip && pip install "poetry>=1.1.7,<2.0.0"
WORKDIR /workspace
RUN poetry config virtualenvs.create false
COPY ./pyproject.toml .
RUN poetry install --no-dev
EXPOSE 8000
CMD ["/bin/bash", "scripts/start-dev.sh"]