"""empty message

Revision ID: 42ecd75e599d
Revises: a20435488d9b
Create Date: 2021-11-30 23:09:18.593410

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "42ecd75e599d"
down_revision = "a20435488d9b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("course_unique", "course", ["evaluator", "name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("course_unique", "course", type_="unique")
    # ### end Alembic commands ###
