"""empty message

Revision ID: 51f7a62dd6ac
Revises: 64f39352e304
Create Date: 2021-11-27 23:47:53.781021

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "51f7a62dd6ac"
down_revision = "64f39352e304"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("course", sa.Column("survey_config", sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, "course", "survey_config", ["survey_config"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "course", type_="foreignkey")
    op.drop_column("course", "survey_config")
    # ### end Alembic commands ###
