"""empty message

Revision ID: ca9dcd553561
Revises: dbd294f658e2
Create Date: 2021-12-01 22:46:49.612666

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ca9dcd553561"
down_revision = "dbd294f658e2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "coursexstudent_unique", "coursexstudent", ["course", "student"]
    )
    op.create_unique_constraint("groupxuser_unique", "groupxuser", ["group", "member"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("groupxuser_unique", "groupxuser", type_="unique")
    op.drop_constraint("coursexstudent_unique", "coursexstudent", type_="unique")
    # ### end Alembic commands ###
