"""empty message

Revision ID: dbd294f658e2
Revises: 49e791063766
Create Date: 2021-12-01 21:16:01.636212

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "dbd294f658e2"
down_revision = "49e791063766"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "coursexstudent",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("course", sa.INTEGER(), nullable=True),
        sa.Column("student", postgresql.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course"],
            ["course.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("coursexstudent")
    # ### end Alembic commands ###
