name: deploy

on:
  push:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      
      - name: Build the Docker image
        env:
          ECR_REGISTRY: 376119282775.dkr.ecr.ap-northeast-2.amazonaws.com
          ECR_REPOSITORY: per4mance-main-server
        run: |
          export IMAGE_TAG=$(date "+%Y-%m-%d.%H%M")
          docker build . --file Dockerfile.dev --tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
